name: CI
run-name: ${{ github.actor }} is running GitHub Actions
on: 
    push:
        branches: [ "develop" ]
    pull_request:
        branches: [ "develop" ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 18
              uses: actions/setup-node@v4
              with: 
                node-version: '18.x'
            - run: yarn
            - run: yarn build
            - run: yarn test
